# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Ermöglicht die Verwendung von Kalendern (ICS)'
        en: ''
    maintainer: cmalo (mknx)
    tester: ohinckel
    state: ready
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: iCal                # class containing the plugin

parameters:
# Definition of parameters to be configured in etc/plugin.yaml
    cycle:
        type: int
        default: 3600
        description:
            de: "Zykluszeit in Sekunden"
            en: "Cycle time in seconds"
    calendars:
        type: list(str)
        description:
            de: "Liste der Kalenderdateien (Beispiele: private:http://example.com/private.ics, http://example.com/public.ics, holiday:http://example.com/holidays.ics)"
            en: "List of calender files (Examples: private:http://example.com/private.ics, http://example.com/public.ics, holiday:http://example.com/holidays.ics)"


item_attributes:
# Definition of item attributes defined by this plugin
    ical_calendar:
        type: str
        descripton:
            de: ""
            en: "Configures a connection between the item and the given calendar. You can specify the calendar URI or \
                the calendar alias (holiday, private). The configured calendar will automatically be added to the \
                internal calendar cache and will automatically be updated.

                When configured, each time an event is taken place at the moment, the item will be set to true or if \
                not, to false.

                The update interval for the item updates is currently at one minutes. Which means each minutes it \
                will be checked if an event is take place and the items will be updated."

plugin_functions:
# Definition of plugin functions defined by this plugin

logic_parameters: NONE
# Definition of logic parameters defined by this plugin

