# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Husqvarna Automower Plugin'
        en: 'Husqvarna Automower Plugin'
    maintainer: gama 
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.6.0                  # Plugin version
    sh_minversion: 1.4              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True 
    classname: Husky         # class containing the plugin

parameters:
    userid:
        type: str
        default: ''
        description:
            de: 'Benutzer ID für den Husqvarna Service'
            en: ''
    password:
        type: str
        default: ''
        hide: True
        description:
            de: 'Passwort für den Login'
            en: 'Password for login'
    device:
        type: str
        default: ''
        description:
            de: '(optional) ID oder Name des Mähroboters'
            en: '(optional) id or name of the automower'

    mapkey:
        type: str
        default: ''
        description:
            de: '(optional) google maps api key'
            en: '(optional) google maps api key'


item_attributes: NONE
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)

